#!/usr/bin/env python3
"""Generate a real GitHub contribution SVG with a five-cell red snake.

The SVG uses the authenticated GitHub GraphQL API. It is designed for a
GitHub profile README and can be regenerated by GitHub Actions.
"""
import json
import os
import sys
import urllib.request
from pathlib import Path

USER = os.getenv("PROFILE_USER", "terminalxo")
TOKEN = os.getenv("GITHUB_TOKEN")
OUT = Path(os.getenv("HEATMAP_OUT", "assets/live-heatmap.svg"))

if not TOKEN:
    raise SystemExit("GITHUB_TOKEN is required")

query = r'''
query($login:String!) {
  user(login:$login) {
    contributionsCollection {
      contributionCalendar {
        weeks {
          contributionDays {
            contributionCount
            date
            weekday
          }
        }
      }
    }
  }
}
'''

payload = json.dumps({"query": query, "variables": {"login": USER}}).encode()
req = urllib.request.Request(
    "https://api.github.com/graphql",
    data=payload,
    headers={
        "Authorization": f"bearer {TOKEN}",
        "Content-Type": "application/json",
        "User-Agent": "terminalxo-profile-readme",
    },
)
with urllib.request.urlopen(req) as response:
    body = json.load(response)
if body.get("errors"):
    raise SystemExit(body["errors"])

weeks = body["data"]["user"]["contributionsCollection"]["contributionCalendar"]["weeks"]
if not weeks:
    raise SystemExit("No contribution data returned")

counts = [d["contributionCount"] for w in weeks for d in w["contributionDays"]]
max_count = max(counts) if counts else 1

CELL, GAP = 11, 4
LEFT, TOP = 42, 68
NW = len(weeks)
WIDTH = LEFT * 2 + NW * (CELL + GAP)
HEIGHT = 255

# Map contribution density to a restrained GitHub-like green palette.
def color_for(n: int) -> str:
    if n <= 0: return "#18181b"
    ratio = n / max_count if max_count else 0
    if ratio <= .25: return "#1f4b2b"
    if ratio <= .50: return "#286338"
    if ratio <= .75: return "#347d46"
    return "#46a35b"

cells = []
coords = []
for wi, week in enumerate(weeks):
    days = {d["weekday"]: d for d in week["contributionDays"]}
    for di in range(7):
        d = days.get(di)
        n = int(d["contributionCount"]) if d else 0
        x = LEFT + wi * (CELL + GAP)
        y = TOP + di * (CELL + GAP)
        cells.append(f'<rect x="{x}" y="{y}" width="{CELL}" height="{CELL}" rx="2" fill="{color_for(n)}"><title>{n} contributions</title></rect>')

# Serpentine path gives a Nokia-Snake-like scan of the entire matrix.
for wi in range(NW):
    day_range = range(7) if wi % 2 == 0 else range(6, -1, -1)
    for di in day_range:
        coords.append((LEFT + wi * (CELL + GAP), TOP + di * (CELL + GAP)))

# SVG discrete x/y animation for five blocks with staggered positions.
dur = max(9.0, len(coords) * 0.028)
N = len(coords)

def anim_values(offset, axis):
    vals=[]
    for i in range(N):
        p=coords[(i-offset) % N]
        vals.append(str(p[0] if axis == 0 else p[1]))
    return ";".join(vals)

snake=[]
for i in range(5):
    opacity = 1 - i * 0.12
    snake.append(f'''
    <rect width="{CELL+2}" height="{CELL+2}" rx="2" fill="#df3541" opacity="{opacity:.2f}">
      <animate attributeName="x" values="{anim_values(i,0)}" dur="{dur:.2f}s" repeatCount="indefinite" calcMode="discrete" />
      <animate attributeName="y" values="{anim_values(i,1)}" dur="{dur:.2f}s" repeatCount="indefinite" calcMode="discrete" />
    </rect>''')

svg=f'''<svg xmlns="http://www.w3.org/2000/svg" width="{WIDTH}" height="{HEIGHT}" viewBox="0 0 {WIDTH} {HEIGHT}">
<style>
  .mono {{ font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace; }}
</style>
<rect width="100%" height="100%" rx="18" fill="#09090b" />
<rect x="1" y="1" width="{WIDTH-2}" height="{HEIGHT-2}" rx="18" fill="none" stroke="#29292f" stroke-width="2" />
<text class="mono" x="28" y="33" font-size="16" fill="#e2ded8">&gt; contribution_matrix --live</text>
<text class="mono" x="{WIDTH-238}" y="33" font-size="13" fill="#d93642">5-CELL RED SNAKE</text>
<line x1="26" y1="48" x2="{WIDTH-26}" y2="48" stroke="#2a2a30" />
{''.join(cells)}
{''.join(snake)}
<text class="mono" x="42" y="210" font-size="12" fill="#77716d">REAL GITHUB CONTRIBUTIONS // AUTO-REFRESHED</text>
<text class="mono" x="{WIDTH-180}" y="210" font-size="12" fill="#d93642">SIGNAL: LIVE_</text>
</svg>'''
OUT.parent.mkdir(parents=True, exist_ok=True)
OUT.write_text(svg, encoding="utf-8")
print(f"wrote {OUT}")
